
(* Unapplied function: An expression with variables needed to be filled for evaluation. 
   Should be generated by the parser. Going back from the relevant statement(s), it 
   reduces the whole function into a single expression. Then, before evaluating this
   expression, it overwrites the state according to local definitions and the given
   argument values. Then, it evaluates the expression and saves the result to the program 
   state. Then, it destructs all local assignments before exiting. *)
type func_unapp = value list -> program_state -> value


(* Abstract syntax tree of python subset *)

and value =
    | IntV of int
    | FloatV of float
    | StringV of string
    | BoolV of bool
    | Ntwo
    | Exception of string
    | Function of func_unapp

and bin_op = 
    | Add
    | Mul
    | Sub
    | Div
    | And
    | Or
    | Less
    | Greater
    | Leq
    | Geq
    | Equal
    | Neq

and expr = 
    | Value of value
    | Bin_Exp of (expr * bin_op * expr)
    | Var_Ref of string
    | Func_App of (string * expr list)

and statement = 
    | Expr of expr
    | Assign of (string * expr)
    | Func_Def of (string * expr)

and program = statement list

(* Program state: Used to keep track of variables (including functions) and current position. *)
and program_state = {
    program: program;
    ip: int;
    variables: (string, expr) Hashtbl.t;
}

(* Helper functions *)

let rec expr_to_str (exp: expr) : string =
    let value_to_str (val_x: value) : string =
        match val_x with
          | IntV x -> string_of_int x
          | FloatV x -> string_of_float x
          | StringV x -> x
          | BoolV x -> string_of_bool x
          | Exception x -> x
          | Ntwo -> "None"
          | Function f -> "Function"
    and bin_op_to_str (op: bin_op) : string =
        match op with
          | Add -> "+"
          | Mul -> "*"
          | Sub -> "-"
          | Div -> "/"
          | And -> "and"
          | Or -> "or"
          | Less -> "<"
          | Greater -> ">"
          | Leq -> "<="
          | Geq -> ">="
          | Equal -> "=="
          | Neq -> "!="
    in 
    match exp with
      | Value x -> value_to_str x
      | Bin_Exp (x1, op, x2) -> "(" ^ (expr_to_str x1) ^ " " ^ (bin_op_to_str op) ^ " " ^ (expr_to_str x2) ^ ")"
      | Var_Ref x -> x
      | Func_App (x, args) -> x ^ "(" ^ String.concat ", " (List.map expr_to_str args) ^ ")"

let value_to_output val_x =
    match val_x with
      | IntV x -> print_int x; print_newline();
      | FloatV x -> print_float x; print_newline();
      | StringV x -> print_string x; print_newline();
      | BoolV x -> print_string (if x then "True" else "False"); print_newline();
      | Exception x -> print_string x; print_newline();
      | Ntwo -> print_string "None"; print_newline();
      | Function f -> print_string "Function"; print_newline();

