
open Base
open Stdio

(* Module description: Abstract syntax tree of python subset.
   A program is a list of statements. Statements can be either of an expression (Expr), 
   an assignment (Assign) or a function definition (Func_Def). When running a program, 
   Assign and Func_Def alter the state of the program (defined in program_state, whilst
   Expr are evaluated. Evaluating an expression must yield a value and is done in a 
   recursive manner.*)

(* func_opaque and func_statements are the two function types. func_opaque is used for 
   functions implemented in OCaml for modules / stdlib. func_statements is used for 
   user-defined functions in python, which contains a list of statements. *)
type func_opaque = program_state -> value [@sexp.opaque]

and func_statements = statement list

(* Unapplied function: Either a user-defined function or a stdlib function. 
   Should be generated by the parser / defined in python stdlib.
   If there is a Exception created at some point, it should be passed up. *)
and func_unapp = 
    | Func_Opq of func_opaque
    | Func_Stat of func_statements
[@@deriving sexp]

(* Function wrapper: Called before applying the function. 
   It overwrites the state according to local definitions and the given
   argument values. It should also check for argument count and other invalidities. *)
and func_oncall = value list -> program_state -> (unit, string) Result.t [@sexp.opaque]

(* Function wrapper: Called after applying the function.
   Destructs all local definitions. *)
and func_offcall = program_state -> (unit, string) Result.t [@sexp.opaque]

and value =
    | IntV of int
    | FloatV of float
    | StringV of string
    | BoolV of bool
    | ListV of value list
    | DictV of value Hashtbl.M(String).t
    | Ntwo
    | Exception of string
    | Function of (func_unapp * func_oncall * func_offcall)
[@@deriving sexp]

and bin_op = 
    | Add
    | Mul
    | Sub
    | Div
    | And
    | Or
    | Less
    | Greater
    | Leq
    | Geq
    | Equal
    | Neq
    | Mod
    | In
[@@deriving sexp]

and expr =
    | Value of value
    | Bin_Exp of (expr * bin_op * expr)
    | Var_Ref of string
    | Func_App of (string * expr list)
    | ListE of expr list
    | DictE of (expr * expr) list
    | AccessE of (expr * expr)
    | SliceE of (expr option * expr option * expr option)
[@@deriving sexp]

and statement =
    | Expr of expr
    | Assign of (string * expr * expr option)
    | Return of expr
    | Func_Def of (string * func_unapp * func_oncall * func_offcall)
    | If of (expr * statement list * statement list)
    | While of (expr * statement list)
    | For of (string * expr * statement list)
    | FunDef of (string * string list * statement list)
    | Pass
[@@deriving sexp]

(* Program state: Used to keep track of variables (including functions) and current position. *)
and program_state = {
    (* Current program. *)
    program: statement list;
    (* Current position in the program. *)
    ip: int;
    (* Pair an indentifier to a history of expressions. *)
    variables: expr list Hashtbl.M(String).t;
    (* Track local variable assignments, such that they can be destructed later. *)
    local_variables: bool Hashtbl.M(String).t; 
}
[@@deriving sexp]

(* Helper functions *)

let rec value_to_output (val_x: value) : unit =
    match val_x with
      | IntV x -> printf "%d\n" x
      | FloatV x -> printf "%f\n" x
      | StringV x -> print_endline x
      | BoolV x -> print_endline (if x then "True" else "False") 
      | Exception x -> print_endline x
      | Ntwo -> print_endline "None"
      | Function f -> print_endline "Function"
      | ListV x -> printf "[%s]\n" (String.concat ~sep:", " (List.map x ~f:(fun x -> value_to_str x)))
      | DictV h -> printf "{%s}\n" (String.concat ~sep:", " (List.map (Hashtbl.to_alist h) ~f:(fun (k, v) -> k^": "^value_to_str v)))

and value_to_str ?(add_paren: bool = false) (val_x: value) : string = 
    match val_x with
      | IntV x -> Int.to_string x
      | FloatV x -> Float.to_string x
      | StringV x -> if add_paren then "\""^x^"\"" else x
      | BoolV x -> if x then "True" else "False"
      | Exception x -> x
      | Ntwo -> "None"
      | Function f -> "Function"
      | ListV x -> "[" ^ String.concat ~sep:", " (List.map x ~f:(fun x -> value_to_str ~add_paren:true x)) ^ "]"
      | DictV h -> "{" ^ String.concat ~sep:", " (List.map (Hashtbl.to_alist h) ~f:(fun (k, v) -> k^": "^value_to_str ~add_paren:true v)) ^ "}"

and expr_to_str (exp: expr) : string =
    let bin_op_to_str (op: bin_op) : string =
        match op with
          | Add -> "+"
          | Mul -> "*"
          | Sub -> "-"
          | Div -> "/"
          | And -> "and"
          | Or -> "or"
          | Less -> "<"
          | Greater -> ">"
          | Leq -> "<="
          | Geq -> ">="
          | Equal -> "=="
          | Neq -> "!="
          | Mod -> "%"
          | In -> "in"
    in 
    match exp with
      | Value x -> value_to_str x
      | Bin_Exp (x1, op, x2) -> "(" ^ (expr_to_str x1) ^ " " ^ (bin_op_to_str op) ^ " " ^ (expr_to_str x2) ^ ")"
      | Var_Ref x -> x
      | Func_App (x, args) -> x ^ "(" ^ String.concat ~sep:", " (List.map args ~f:expr_to_str) ^ ")"
      | ListE x -> "[" ^ String.concat ~sep:", " (List.map x ~f:expr_to_str) ^ "]"
      | AccessE (x1, x2) -> "(" ^ (expr_to_str x1) ^ "[" ^ (expr_to_str x2) ^ "]"
      | DictE x -> "{" ^ String.concat ~sep:", " (List.map x ~f:(fun (k, v) -> (expr_to_str k) ^ ": " ^ (expr_to_str v))) ^ "}"
      | SliceE (s, e, st) ->
          let part = function None -> "" | Some x -> expr_to_str x in
          (match st with
             | None -> (part s) ^ ":" ^ (part e)
             | Some _ -> (part s) ^ ":" ^ (part e) ^ ":" ^ (part st))

let values_to_str ?(add_paren: bool = false) (vals: value list) : string = 
    String.concat ~sep:" " (List.map vals ~f:(fun x -> value_to_str ~add_paren:add_paren x))

let exprs_to_str (exprs: expr list) : string = 
    String.concat ~sep:" " (List.map exprs ~f:expr_to_str)

let rec value_equals (v1:value) (v2:value) : bool = 
    match v1, v2 with
      | IntV x1, IntV x2 -> x1 = x2
      | FloatV x1, FloatV x2 -> Float.equal x1 x2
      | StringV x1, StringV x2 -> String.equal x1 x2
      | BoolV x1, BoolV x2 -> Bool.equal x1 x2
      | Ntwo, Ntwo -> true
      | Exception x1, Exception x2 -> String.equal x1 x2
      | ListV x1, ListV x2 -> List.for_all2_exn x1 x2 ~f:value_equals
      | DictV x1, DictV x2 -> Hashtbl.equal value_equals x1 x2
      | _ -> false
