
open Base
open Stdio

(* Unapplied function: An expression with variables needed to be filled for evaluation. 
   Should be generated by the parser. Going back from the relevant statement(s), it 
   reduces the whole function into a single expression. Then, before evaluating this
   expression, it overwrites the state according to local definitions and the given
   argument values. Then, it evaluates the expression and saves the result to the program 
   state. Then, it destructs all local assignments before exiting. If there is a Exception
   created at some point, it should be passed up. *)
type func_unapp = value list -> program_state -> value


(* Abstract syntax tree of python subset *)

and value =
    | IntV of int
    | FloatV of float
    | StringV of string
    | BoolV of bool
    | Ntwo
    | Exception of string
    | Function of func_unapp

and bin_op = 
    | Add
    | Mul
    | Sub
    | Div
    | And
    | Or
    | Less
    | Greater
    | Leq
    | Geq
    | Equal
    | Neq

and expr = 
    | Value of value
    | Bin_Exp of (expr * bin_op * expr)
    | Var_Ref of string
    | Func_App of (string * expr list)

and statement = 
    | Expr of expr
    | Assign of (string * expr)
    | Func_Def of (string * expr)

and program = statement list

(* Program state: Used to keep track of variables (including functions) and current position. *)
and program_state = {
    program: program;
    ip: int;
    variables: (string, expr) Hashtbl.t;
}

(* Helper functions *)

let rec expr_to_str (exp: expr) : string =
    let value_to_str (val_x: value) : string =
        match val_x with
          | IntV x -> Int.to_string x
          | FloatV x -> Float.to_string x
          | StringV x -> x
          | BoolV x -> Bool.to_string x
          | Exception x -> x
          | Ntwo -> "None"
          | Function f -> "Function"
    and bin_op_to_str (op: bin_op) : string =
        match op with
          | Add -> "+"
          | Mul -> "*"
          | Sub -> "-"
          | Div -> "/"
          | And -> "and"
          | Or -> "or"
          | Less -> "<"
          | Greater -> ">"
          | Leq -> "<="
          | Geq -> ">="
          | Equal -> "=="
          | Neq -> "!="
    in 
    match exp with
      | Value x -> value_to_str x
      | Bin_Exp (x1, op, x2) -> "(" ^ (expr_to_str x1) ^ " " ^ (bin_op_to_str op) ^ " " ^ (expr_to_str x2) ^ ")"
      | Var_Ref x -> x
      | Func_App (x, args) -> x ^ "(" ^ String.concat ~sep:", " (List.map args ~f:expr_to_str) ^ ")"

let value_to_output (val_x: value) : unit =
    match val_x with
      | IntV x -> printf "%d\n" x
      | FloatV x -> printf "%f\n" x
      | StringV x -> print_endline x
      | BoolV x -> print_endline (if x then "True" else "False") 
      | Exception x -> print_endline x
      | Ntwo -> print_endline "None"
      | Function f -> print_endline "Function"

let value_to_str (val_x: value) : string = 
    match val_x with
      | IntV x -> Int.to_string x
      | FloatV x -> Float.to_string x
      | StringV x -> x
      | BoolV x -> Bool.to_string x
      | Exception x -> x
      | Ntwo -> "None"
      | Function f -> "Function"


let values_to_str (vals: value list) : string = 
    String.concat ~sep:" " (List.map vals ~f:value_to_str)
