
(* Unapplied function: An expression with values needed to be filled for evaluation. 
   Should be generated by the parser. Going back from the returning statement(s), it 
   reduces the whole function into a single expression. Then, before evaluating this
   expression, it overwrites the state according to local definitions and the given
   argument values. Then, it evaluates the expression and saves the result to the program 
   state. Then, it destructs all local assignments before exiting. *)
type func_unapp = Ast.value list -> program_state -> Ast.value

(* Program state: Used to keep track of variables, functions and current position. *)
and program_state = {
    program: Ast.program;
    ip: int;
    mutable variables: (string, Ast.expr) Hashtbl.t;
    mutable functions: (string, func_unapp) Hashtbl.t
}
